const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const v5IconPaths={
 list:'<path d="M9 6h11M9 12h11M9 18h11"/><circle cx="4.5" cy="6" r=".7"/><circle cx="4.5" cy="12" r=".7"/><circle cx="4.5" cy="18" r=".7"/>',
 size:'<path d="M3 19 8.5 5 14 19M5 14h7M15 19l2.5-7 2.5 7M16 16h3"/>',
 font:'<path d="M3 5h9M7.5 5v14M4.5 19h6M14 8h7M17.5 8v11M15 19h5"/>',
 book:'<path d="M4 5c3-1 6-.5 8 1v14c-2-1.5-5-2-8-1V5ZM20 5c-3-1-6-.5-8 1v14c2-1.5 5-2 8-1V5Z"/>',
 edit:'<path d="M5 19.5 9 18l10-10-3-3L6 15l-1 4.5ZM13.8 7.2l3 3"/>'
};
const v5Icon=paths=>`<svg viewBox="0 0 24 24" aria-hidden="true">${paths}</svg>`;
const shelfIconPaths={add:'<path d="M3 5h7c2 0 3 1 3 3v13c-1-2-3-3-5-3H3zM21 5h-6c-1 0-2 .3-2 1M18 12v8M14 16h8"/>',check:'<path d="M3 5h7c2 0 3 1 3 3v13c-1-2-3-3-5-3H3zM21 5h-6c-1 0-2 .3-2 1M15 14l2 2 4-5"/>'};
const icons={list:v5Icon(v5IconPaths.list),size:v5Icon(v5IconPaths.size),font:v5Icon(v5IconPaths.font),add:v5Icon(shelfIconPaths.add),check:v5Icon(shelfIconPaths.check),edit:v5Icon(v5IconPaths.edit)};
let books=[], route='', renderedHash='', openMenu='', pop='', drawer=false, modal=null, toastTimer, saveTimer, editDraft=null, editOrigin='#shelf', detailOrigin='#discover', searchShelf='',searchDiscover='',filterShelf='all',reviewTab='done',scrollMemory={};
const key='jianshan-books-v2';
let data={shelf:{},positions:{},settings:{size:20,font:'serif'}};
try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&typeof saved==='object')data={...data,...saved,settings:{...data.settings,...saved.settings}}}catch(e){}
function persist(){try{localStorage.setItem(key,JSON.stringify(data));return true}catch(e){toast('保存失败，请检查浏览器存储空间');return false}}
function toast(message){document.querySelector('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.textContent=message;document.body.append(el);clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.remove(),3000)}
function book(id){return books.find(x=>x.id===id)}
function member(id){return data.shelf[id]}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function addBook(id,fromReader=false){if(member(id))return;if(fromReader)savePosition();data.shelf[id]={status:data.positions[id]||fromReader?'reading':'unread',addedAt:Date.now(),updatedAt:Date.now(),thought:'',rating:0,finished:''};if(persist()){toast('已加入书架');render()}}
function removeBook(id){const b=book(id);if(!b||!member(id))return;showModal('移出书架？',`移出《${b.title}》会清除这本书的阅读记录和阅读位置。`,'移出书架',()=>{delete data.shelf[id];delete data.positions[id];persist();toast('已移出书架');render()})}
function statusName(s){return {unread:'未读',reading:'在读',done:'已读'}[s]||'未读'}
function nav(active){return `<header class="topbar"><div class="nav-inner"><a class="brand" href="#shelf" title="返回我的书架">见山书房</a><nav class="nav" aria-label="主导航"><a class="${active==='shelf'?'active':''}" href="#shelf">我的书架</a><a class="${active==='discover'?'active':''}" href="#discover">发现与添加</a><a class="${active==='review'?'active':''}" href="#review">阅读回顾</a></nav><span class="nav-note">一处留给阅读的地方</span></div></header>`}
const art={zhaohua:['zhaohua-xishi','#E5CF9F','#3E392F'],liaozhai:['liaozhai-zhiyi','#173C40','#FAF2E5'],pride:['pride-prejudice','#BBA9A2','#3A3833'],shanhai:['shanhaijing','#E5D7B5','#344A43'],alice:['alice-wonderland','#B7D3DB','#284752'],nahan:['nahan','#9A271F','#FFF7E8'],aesop:['aesop-fables','#E8C677','#52452C'],grimm:['grimm-tales','#192D45','#FFF2D7'],sea:['twenty-thousand-leagues','#12434B','#F5E9D4'],oz:['wizard-of-oz','#8AB88B','#2F553E']};
const figmaCopy={
 zhaohua:['散文集','在记忆里拾起那些温柔而鲜明的旧时光。'],
 liaozhai:['志怪小说','狐鬼花妖之间，照见人间的百般情意。'],
 pride:['经典小说','关于误解、成长与重新认识彼此。'],
 shanhai:['古籍','循山川的名字，想象世界最初的模样。'],
 alice:['童话','跟随一只白兔，落入奇异又明亮的梦。'],
 nahan:['小说集','在清醒而有力的文字中，听见时代的声音。'],
 aesop:['寓言','短小的故事里，藏着值得反复品读的智慧。'],
 grimm:['童话','穿过森林与城堡，重逢经典的想象。'],
 sea:['科幻小说','跟随鹦鹉螺号，去往深蓝色的未知。'],
 oz:['童话','踏上黄砖路，寻找勇气、心与归处。']
};
const figmaType=b=>figmaCopy[b.id]?.[0]||b.genre;
const figmaDescription=b=>figmaCopy[b.id]?.[1]||b.description;
function cover(b){const [file,bg,ink]=art[b.id];return `<div class="cover cover-${b.id}" style="--cover:${bg};--ink:${ink}"><img src="./assets/${file}.png" alt="" class="cover-art"><span class="cover-spine"></span></div>`}
function card(b,mode='discover'){const shelf=mode==='shelf';return `<article class="book-card"><a class="cover-link" href="${shelf?'#read/'+b.id:'#book/'+b.id}" aria-label="${shelf?'阅读':'查看'}${esc(b.title)}">${cover(b)}</a><div class="book-caption"><div><a class="book-title" href="#book/${b.id}">${esc(b.title)}</a><div class="book-author">${esc(b.author)}</div></div>${shelf?`<div class="more-wrap"><button class="more" data-action="menu" data-id="${b.id}" aria-label="${esc(b.title)}更多操作" aria-expanded="${openMenu===b.id}">⋯</button>${openMenu===b.id?`<div class="menu"><button data-action="detail" data-id="${b.id}">书籍详情</button><button data-action="edit" data-id="${b.id}">编辑阅读记录</button><button data-action="remove" data-id="${b.id}">移出书架</button></div>`:''}</div>`:''}</div>${!shelf?`<p class="book-desc">${esc(figmaDescription(b))}</p>`:''}</article>`}
function empty(title,copy,button,href){return `<div class="empty"><img class="empty-image" src="./assets/empty-library.png" alt=""><h2>${title}</h2><p>${copy}</p><a class="btn" href="${href}">${button} ↗</a></div>`}
function shelfPage(){
 const mine=books.filter(b=>member(b.id));
 const list=mine.filter(b=>(filterShelf==='all'||member(b.id).status===filterShelf)&&(`${b.title} ${b.author}`.toLowerCase().includes(searchShelf.trim().toLowerCase())));
 const recent=mine.filter(b=>data.positions[b.id]).sort((a,b)=>data.positions[b.id].updatedAt-data.positions[a.id].updatedAt)[0]||mine[0];
 return nav('shelf')+`<main class="container shelf-page"><div class="page-head"><h1>我的书架</h1>${mine.length?'<a class="btn shelf-add" href="#discover">＋ 添加书籍</a>':''}</div>${!mine.length?empty('从一本书开始，慢慢把日子读厚。','把喜欢的书收进来，这里会成为只属于你的阅读角落。','去发现书籍','#discover'):`<section class="recent-section"><div class="section-header"><h2>最近阅读</h2></div><div class="recent"><a class="cover-link" href="#read/${recent.id}">${cover(recent)}</a><div class="recent-content"><h3>${esc(recent.title)}</h3><p>${esc(recent.author)} · ${esc(figmaType(recent))}</p><p>${data.positions[recent.id]?'上次读到':'尚未开始'} · ${esc(recent.chapters[data.positions[recent.id]?.chapter||0]?.title||recent.chapters[0].title)}</p><a class="btn" href="#read/${recent.id}">${data.positions[recent.id]?'继续阅读':'开始阅读'} ↗</a></div><div class="recent-quote">在字里，重新遇见旧时的自己。</div></div></section><section class="shelf-catalog"><div class="section-header"><h2>全部藏书</h2></div><div class="tabs" role="tablist" aria-label="阅读状态筛选">${[['all','全部'],['unread','未读'],['reading','在读'],['done','已读']].map(([v,t])=>`<button class="tab ${filterShelf===v?'active':''}" data-action="filter" data-value="${v}" role="tab" aria-selected="${filterShelf===v}">${t}</button>`).join('')}</div><input class="search" id="shelf-search" aria-label="搜索我的书架" placeholder="搜索书名或作者" value="${esc(searchShelf)}">${list.length?`<div class="book-grid">${list.map(b=>card(b,'shelf')).join('')}</div>`:''}</section>`}</main>`
}
function discoverPage(){
 const q=searchDiscover.trim().toLowerCase();
 const list=books.filter(b=>`${b.title} ${b.author}`.toLowerCase().includes(q));
 return nav('discover')+`<main class="container discover-page"><div class="page-head"><h1>发现与添加</h1><input class="search" id="discover-search" aria-label="搜索书库" placeholder="搜索书名或作者" value="${esc(searchDiscover)}"></div>${!q?`<section class="recommend-section"><div class="section-header"><h2>精选推荐</h2><span class="section-hint">三本适合在今天翻开的书</span></div><div class="recommendations">${['zhaohua','liaozhai','pride'].map(id=>{const b=book(id);return `<a class="recommend" href="#book/${id}">${cover(b)}<div class="rec-copy"><small>编辑推荐</small><h3>${esc(b.title)}</h3><span>${esc(b.author)} · ${esc(figmaType(b))}</span><p>${esc(figmaDescription(b))}</p></div></a>`}).join('')}</div></section><section class="discover-catalog"><div class="section-header"><h2>全部书籍</h2><span class="section-hint">在书页之间，遇见新的风景。</span></div>`:`<section class="discover-catalog search-results"><div class="section-header"><h2>搜索结果</h2></div>`}${list.length?`<div class="book-grid five">${list.map(b=>card(b)).join('')}</div>`:empty('没有找到这本书','换一个书名或作者试试。','清空搜索','#discover')}</section></main>`
}
function detailPage(b){if(!b)return nav('')+empty('书籍不存在','','返回书架','#shelf');const m=member(b.id),pos=data.positions[b.id];return nav('')+`<main class="narrow detail"><button class="back" data-action="back-detail">← 返回${detailOrigin==='#discover'?'发现与添加':detailOrigin==='#shelf'?'我的书架':'上一页'}</button><div class="detail-top">${cover(b)}<div><div class="detail-kicker">${esc(b.genre)} · 在线阅读</div><h1>${esc(b.title)}</h1><div class="detail-meta">${esc(b.author)}　著</div><p class="detail-desc">${b.id==='zhaohua'?'在纷繁的日常里，拾起关于童年、亲情与旧友的记忆。十篇散文，从百草园的草木，到三味书屋的旧时光，以温柔而清醒的笔触，写下一个人的来路。':esc(b.description+' '+b.bio)}</p></div><div class="detail-actions"><button class="btn ${m?'subtle':''}" data-action="toggle-shelf" data-id="${b.id}" aria-label="${m?'移出书架':'加入书架'}">${m?'移出书架':'加入书架'}</button><a class="btn light" href="#read/${b.id}">${pos?'继续阅读':'开始阅读'} ↗</a><span class="source-note">提供在线示例正文 · ${b.chapters.length} 个章节</span></div></div><div class="detail-status"><strong>我的阅读状态</strong>${m?`<div class="tabs" style="margin:0">${[['unread','未读'],['reading','在读'],['done','已读']].map(([v,t])=>`<button class="tab ${m.status===v?'active':''}" data-action="status" data-id="${b.id}" data-value="${v}">${t}</button>`).join('')}</div>`:'<span class="helper">加入书架后可记录</span>'}</div><div class="detail-sections"><section><h2>关于作者</h2><p>${esc(b.id==='zhaohua'?'鲁迅（1881—1936），中国现代文学的重要作家。\n他的文字既有敏锐的观察，也留存着对旧日人事的深情。':b.bio)}</p></section><section><h2>示例章节</h2>${b.chapters.map((c,i)=>`<a class="chapter-row" href="#read/${b.id}/${i}"><span>${esc(c.title)}</span><span>↗</span></a>`).join('')}</section></div></main>`}
function toolButton(kind,label,action,b){return `<div class="tool-wrap"><button class="iconbtn ${pop===kind?'on':''}" data-action="${action}" ${b?`data-id="${b.id}"`:''} aria-label="${label}" title="${label}">${icons[kind]}</button>${pop===kind?`<div class="pop">${kind==='size'?[18,20,22].map(n=>`<button class="${data.settings.size===n?'chosen':''}" data-action="size-set" data-value="${n}">${n} px</button>`).join(''):kind==='font'?[['serif','思源宋体','var(--serif)'],['sans','思源黑体','var(--sans)'],['kai','霞鹜文楷','"LXGW WenKai",KaiTi,serif']].map(([v,t,f])=>`<button class="${data.settings.font===v?'chosen':''}" style="font-family:${f}" data-action="font-set" data-value="${v}">${t}</button>`).join(''):''}</div>`:''}</div>`}
function readerPage(b,index){if(!b)return empty('书籍不存在','','返回书架','#shelf');const c=b.chapters[index]||b.chapters[0],m=member(b.id),font={serif:'var(--serif)',sans:'var(--sans)',kai:'"LXGW WenKai",KaiTi,serif'}[data.settings.font]||'var(--serif)';return `<div class="reader"><div class="reader-toolbar"><div class="reader-toolbar-inner"><a class="reader-brand" href="#shelf" title="返回我的书架">见山书房</a><a class="reader-book" href="#book/${b.id}" title="书籍详情">${esc(b.title)}</a><div class="reader-tools">${toolButton('list','目录','drawer',b)}${toolButton('size','字号','pop-size',b)}${toolButton('font','字体','pop-font',b)}${toolButton(m?'check':'add',m?'移出书架':'加入书架','toggle-shelf',b)}${toolButton('edit','编辑阅读记录','edit',b)}</div></div></div><div class="reader-paper"><main class="reader-inner"><div class="reader-eyebrow">${esc(b.title)}</div><h1>${esc(c.title)}</h1><div class="reader-prose ${['pride','alice','grimm','sea','oz'].includes(b.id)?'en':''}" style="--reader-size:${data.settings.size}px;--reader-font:${font}">${c.paragraphs.map((p,i)=>`<p id="para-${i}" data-paragraph="${i}">${esc(p)}</p>`).join('')}</div><div class="reader-end">${index===b.chapters.length-1?'示例内容已结束。读完示例不会自动标记整本书为已读。':'本章结束'}<br><a href="${esc(c.source)}" target="_blank" rel="noopener noreferrer">查看文本来源 ↗</a>${index===b.chapters.length-1?`　·　<a href="#book/${b.id}">查看书籍详情</a>　·　<a href="#edit/${b.id}">编辑阅读记录</a>`:''}</div><div class="chapter-nav"><button class="btn subtle" data-action="chapter" data-id="${b.id}" data-value="${index-1}" ${index===0?'disabled':''}>← 上一章</button><button class="btn light" data-action="chapter" data-id="${b.id}" data-value="${index+1}" ${index===b.chapters.length-1?'disabled':''}>下一章 →</button></div></main></div>${drawer?`<div class="reader-drawer" data-action="close-drawer"><aside class="drawer-body" role="dialog" aria-label="章节目录"><div class="drawer-head">章节目录<button data-action="close-drawer" aria-label="关闭目录">×</button></div>${b.chapters.map((ch,i)=>`<button class="drawer-chapter ${i===index?'on':''}" data-action="chapter" data-id="${b.id}" data-value="${i}">${String(i+1).padStart(2,'0')}　${esc(ch.title)}</button>`).join('')}</aside></div>`:''}</div>`}
function editPage(b){if(!b)return empty('书籍不存在','','返回书架','#shelf');const m=member(b.id)||{status:'unread',thought:'',rating:0,finished:''};if(!editDraft||editDraft.id!==b.id)editDraft={id:b.id,status:m.status,thought:m.thought||'',rating:m.rating||0,finished:m.finished||today()};return `<div class="topbar"><div class="nav-inner"><a class="brand" href="#shelf">见山书房</a></div></div><main class="narrow editor"><button class="back" data-action="edit-cancel">← 返回</button><div class="editor-top"><h1>${esc(b.title)}</h1><p>${esc(b.author)} · 编辑阅读记录</p></div><form id="edit-form"><div class="field"><span class="field-title">阅读状态</span><div class="tabs">${[['unread','未读'],['reading','在读'],['done','已读']].map(([v,t])=>`<button type="button" class="tab ${editDraft.status===v?'active':''}" data-action="draft-status" data-value="${v}">${t}</button>`).join('')}</div></div><div class="field"><label for="thought">阅读感想</label><textarea id="thought" maxlength="500" placeholder="写下你的想法…">${esc(editDraft.thought)}</textarea><div class="count"><span id="thought-count">${editDraft.thought.length}</span> / 500</div></div><div class="field"><span class="field-title">个人评分</span><div class="stars" aria-label="个人评分">${[1,2,3,4,5].map(n=>`<button type="button" class="star ${editDraft.rating>=n?'active':''}" data-action="star" data-value="${n}" aria-label="${n} 星" aria-pressed="${editDraft.rating>=n}">★</button>`).join('')}<button type="button" class="text-button" data-action="star" data-value="0">清除</button></div></div><div class="field"><label for="finished">完成日期</label><input type="date" id="finished" value="${esc(editDraft.finished||today())}" max="${today()}"></div><div class="form-actions"><button type="button" class="btn subtle" data-action="edit-cancel">取消</button><button type="submit" class="btn">保存记录</button></div></form></main>`}
function reviewPage(){
 const items=books.filter(b=>{const m=member(b.id);return m&&(reviewTab==='done'?m.status==='done':m.status!=='done')}).sort((a,b)=>{let x=member(a.id),y=member(b.id);return reviewTab==='done'?String(y.finished).localeCompare(String(x.finished)):y.updatedAt-x.updatedAt});
 return nav('review')+`<main class="container review-page"><div class="page-head"><h1>阅读回顾</h1></div><div class="tabs" role="tablist" aria-label="回顾类别"><button class="tab ${reviewTab==='done'?'active':''}" data-action="review-tab" data-value="done" role="tab" aria-selected="${reviewTab==='done'}">已读书籍</button><button class="tab ${reviewTab==='pending'?'active':''}" data-action="review-tab" data-value="pending" role="tab" aria-selected="${reviewTab==='pending'}">未读书籍 · 含在读</button></div>${items.length?`<div class="review-list">${items.map(b=>{const m=member(b.id);return `<article class="review-item"><a class="review-cover" href="#book/${b.id}">${cover(b)}</a><div class="review-copy"><a href="#book/${b.id}"><h3>${esc(b.title)}</h3></a><div class="review-date">${m.status==='done'?`完成于 ${esc(m.finished||'未填写日期')}`:`${statusName(m.status)} · 尚未完成`}</div><div class="review-stars" aria-label="${m.rating||0} 星评分">${'★'.repeat(m.rating||0)}${'☆'.repeat(5-(m.rating||0))}</div><p class="review-note">${m.thought?esc(m.thought.slice(0,80)):'还没有写下阅读感想'}${m.thought.length>80?`<span class="review-extra" hidden>${esc(m.thought.slice(80))}</span> <button class="text-button" data-action="expand">展开</button>`:''}</p></div><button class="btn subtle review-edit" data-action="edit" data-id="${b.id}">编辑阅读记录</button></article>`}).join('')}</div>`:empty(reviewTab==='done'?'读完一本，留下一点感想':'暂时没有未完成的书','书架里的阅读记录会出现在这里。','返回书架','#shelf')}</main>`
}
function routeParts(){return (location.hash.slice(1)||'shelf').split('/')}
function currentRead(){const p=routeParts();return p[0]==='read'?{id:p[1],chapter:Number(p[2]||0)}:null}
function savePosition(){const r=currentRead();if(!r)return;const b=book(r.id);if(!b)return;const paras=[...document.querySelectorAll('[data-paragraph]')];if(!paras.length)return;let anchor=paras[0];for(const p of paras){if(p.getBoundingClientRect().top<=150)anchor=p;else break}const rect=anchor.getBoundingClientRect();const fraction=Math.max(0,Math.min(1,(150-rect.top)/Math.max(rect.height,1)));data.positions[r.id]={chapter:r.chapter,paragraph:Number(anchor.dataset.paragraph),fraction,updatedAt:Date.now()};if(member(r.id)&&member(r.id).status==='unread'){data.shelf[r.id].status='reading';data.shelf[r.id].updatedAt=Date.now()}persist()}
function restorePosition(id,chapter,forceStart=false){if(forceStart){window.scrollTo(0,0);return}const pos=data.positions[id];if(!pos||pos.chapter!==chapter){window.scrollTo(0,0);return}const run=()=>{const p=document.getElementById('para-'+pos.paragraph);if(p){const y=window.scrollY+p.getBoundingClientRect().top-150+Math.max(0,Math.min(1,pos.fraction||0))*p.getBoundingClientRect().height;window.scrollTo(0,Math.max(0,y))}};run();requestAnimationFrame(()=>{run();document.fonts?.ready.then(run)})}
function rememberScroll(){if(route&&route!=='read')scrollMemory[location.hash||'#shelf']=window.scrollY}
function go(hash,forceStart=false){if(currentRead())savePosition();rememberScroll();openMenu='';pop='';drawer=false;if(hash===location.hash){render(forceStart);return}location.hash=hash;window.__forceStart=forceStart}
function render(forceStart=false){const [page,id,num]=routeParts();const sameView=renderedHash===location.hash,previousY=window.scrollY;route=page;renderedHash=location.hash;const b=book(id);let html=page==='discover'?discoverPage():page==='book'?detailPage(b):page==='read'?readerPage(b,Math.max(0,Math.min(Number(num||0),b?.chapters.length-1||0))):page==='edit'?editPage(b):page==='review'?reviewPage():shelfPage();$('#app').innerHTML=html+(modal?modalHtml():'');if(sameView)window.scrollTo(0,previousY);else if(page!=='read')window.scrollTo(0,scrollMemory[location.hash]||0);document.title=(b?b.title+' · ':'')+'见山书房';if(page==='read'){if(sameView&&!forceStart)requestAnimationFrame(()=>window.scrollTo(0,previousY));else restorePosition(id,Number(num||0),forceStart||!!num&&window.__forceStart)}else requestAnimationFrame(()=>{window.scrollTo(0,sameView?previousY:scrollMemory[location.hash]||0);if(page==='shelf'&&openMenu)document.querySelector('.shelf-page .menu')?.scrollIntoView({block:'nearest'})});window.__forceStart=false}
function modalHtml(){return `<div class="modal"><div class="modal-box" role="dialog" aria-modal="true"><h2>${esc(modal.title)}</h2><p>${esc(modal.message)}</p><div class="modal-actions"><button class="btn subtle" data-action="modal-cancel">取消</button><button class="btn" data-action="modal-confirm">${esc(modal.confirm||'确定')}</button></div></div></div>`}
function showModal(title,message,confirm,fn){modal={title,message,confirm,fn};render()}
function startEdit(id){editOrigin=location.hash||'#shelf';editDraft=null;delete scrollMemory['#edit/'+id];go('#edit/'+id)}
function cancelEdit(){const b=book(editDraft?.id),m=member(b?.id)||{status:'unread',thought:'',rating:0,finished:''};const dirty=editDraft&&(editDraft.status!==m.status||editDraft.thought!==(m.thought||'')||editDraft.rating!==(m.rating||0)||editDraft.status==='done'&&editDraft.finished!==(m.finished||''));if(dirty)showModal('放弃未保存的修改？','这次填写的内容将不会保留。','放弃修改',()=>{editDraft=null;go(editOrigin)});else{editDraft=null;go(editOrigin)}}
function setDraftRating(value){if(!editDraft)return;editDraft.rating=Math.max(0,Math.min(5,value));document.querySelectorAll('.editor .star').forEach(star=>{const on=Number(star.dataset.value)<=editDraft.rating;star.classList.toggle('active',on);star.setAttribute('aria-pressed',String(on))})}
function ratingAt(clientX){const stars=[...document.querySelectorAll('.editor .star')];if(!stars.length)return 0;for(let i=0;i<stars.length;i++){if(clientX<stars[i].getBoundingClientRect().right)return i+1}return 5}
let ratingPointer=null;
document.addEventListener('pointerdown',e=>{const star=e.target.closest('.editor .star');if(!star)return;const row=star.closest('.stars');ratingPointer=e.pointerId;row.setPointerCapture(e.pointerId);setDraftRating(ratingAt(e.clientX));e.preventDefault()});
document.addEventListener('pointermove',e=>{if(ratingPointer!==e.pointerId)return;setDraftRating(ratingAt(e.clientX))});
document.addEventListener('pointerup',e=>{if(ratingPointer===e.pointerId){setDraftRating(ratingAt(e.clientX));ratingPointer=null}});
document.addEventListener('pointercancel',e=>{if(ratingPointer===e.pointerId)ratingPointer=null});
document.addEventListener('click',e=>{const link=e.target.closest('a[href^="#"]');if(link&&link.getAttribute('href')!==location.hash)rememberScroll();if(link&&currentRead()){savePosition();if(link.getAttribute('href').startsWith('#book/'))detailOrigin=location.hash;if(link.getAttribute('href').startsWith('#edit/')){editOrigin=location.hash;editDraft=null}}const target=e.target.closest('[data-action]');if(!target){if(openMenu||pop){if(currentRead())savePosition();openMenu='';pop='';render()}return}const a=target.dataset.action,id=target.dataset.id,v=target.dataset.value;if(a==='menu'){openMenu=openMenu===id?'':id;render();return}if(a==='detail'){detailOrigin=location.hash;go('#book/'+id);return}if(a==='back-detail'){go(detailOrigin||'#discover');return}if(a==='edit'){startEdit(id);return}if(a==='edit-cancel'){cancelEdit();return}if(a==='toggle-shelf'){if(member(id))removeBook(id);else addBook(id,!!currentRead());return}if(a==='remove'){removeBook(id);return}if(a==='filter'){filterShelf=v;render();return}if(a==='review-tab'){reviewTab=v;render();return}if(a==='status'){const m=member(id);if(!m||m.status===v)return;const set=()=>{m.status=v;m.updatedAt=Date.now();if(v==='done')m.finished=m.finished||today();else{m.finished='';m.rating=0}persist();render()};if(m.status==='done'&&v!=='done')showModal('更改阅读状态？','改为未读或在读后，个人评分和完成日期会清除。','更改状态',set);else set();return}if(a==='drawer'){savePosition();drawer=true;render();return}if(a==='close-drawer'){if(target.classList.contains('drawer-body'))return;savePosition();drawer=false;render();return}if(a==='pop-size'||a==='pop-font'){savePosition();pop=pop===(a==='pop-size'?'size':'font')?'':a==='pop-size'?'size':'font';render();return}if(a==='size-set'){savePosition();data.settings.size=Number(v);persist();pop='';render();return}if(a==='font-set'){savePosition();data.settings.font=v;persist();pop='';render();return}if(a==='chapter'){go('#read/'+id+'/'+v,true);return}if(a==='draft-status'){editDraft.status=v;if(v==='done'&&!editDraft.finished)editDraft.finished=today();render();return}if(a==='star'){setDraftRating(Number(v));return}if(a==='expand'){const span=target.previousElementSibling;span.hidden=false;target.remove();return}if(a==='modal-cancel'){modal=null;render();return}if(a==='modal-confirm'){const fn=modal.fn;modal=null;fn();return}});
let searchFrame=0,searchComposing=false;
function queueSearch(input){cancelAnimationFrame(searchFrame);searchFrame=requestAnimationFrame(()=>{if(!input.isConnected)return;const id=input.id,position=input.selectionStart,focused=document.activeElement===input;if(id==='shelf-search')searchShelf=input.value;else if(id==='discover-search')searchDiscover=input.value;else return;render();const next=document.getElementById(id);if(focused&&next){next.focus({preventScroll:true});next.setSelectionRange(position,position)}})}
document.addEventListener('compositionstart',e=>{if(e.target.id==='shelf-search'||e.target.id==='discover-search')searchComposing=true});
document.addEventListener('compositionend',e=>{if(e.target.id==='shelf-search'||e.target.id==='discover-search'){searchComposing=false;queueSearch(e.target)}});
document.addEventListener('input',e=>{if(e.target.id==='shelf-search'||e.target.id==='discover-search'){if(!searchComposing&&!e.isComposing)queueSearch(e.target)}if(e.target.id==='thought'){editDraft.thought=e.target.value;$('#thought-count').textContent=e.target.value.length}if(e.target.id==='finished')editDraft.finished=e.target.value});
document.addEventListener('submit',e=>{if(e.target.id!=='edit-form')return;e.preventDefault();const d=editDraft,b=book(d.id),old=member(d.id);if(d.thought.length>500){toast('阅读感想不能超过 500 字');return}if(d.status==='done'&&(!d.finished||d.finished>today())){toast('请填写不晚于今天的完成日期');return}const save=()=>{const now=Date.now();data.shelf[d.id]={...(old||{addedAt:now}),status:d.status,thought:d.thought,rating:d.rating,finished:d.status==='done'?d.finished:'',updatedAt:now,thoughtUpdatedAt:d.thought!==(old?.thought||'')?now:old?.thoughtUpdatedAt||null};if(!persist())return;editDraft=null;toast('阅读记录已保存');go(editOrigin)};if(old?.status==='done'&&d.status!=='done'&&(old.rating||old.finished))showModal('更改阅读状态？','保存后将清除个人评分和完成日期，阅读感想会保留。','继续保存',save);else save()});
window.addEventListener('hashchange',()=>{const [p,id,num]=routeParts();if(p==='book'&&route!=='book'){if(route==='discover')detailOrigin='#discover';else if(route==='shelf')detailOrigin='#shelf';else if(route==='review')detailOrigin='#review';else if(route==='read'&&!detailOrigin.startsWith('#read/'))detailOrigin='#read/'+id+'/'+(data.positions[id]?.chapter||0)}if(p==='read'&&member(id)&&member(id).status==='unread'){data.shelf[id].status='reading';data.shelf[id].updatedAt=Date.now();persist()}render(!!num&&window.__forceStart)});
window.addEventListener('scroll',()=>{if(!currentRead())return;clearTimeout(saveTimer);saveTimer=setTimeout(savePosition,500)},{passive:true});
document.addEventListener('visibilitychange',()=>{if(document.hidden)savePosition()});window.addEventListener('beforeunload',savePosition);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(modal){modal=null;render()}else if(drawer||pop||openMenu){drawer=false;pop='';openMenu='';render()}}});
books=window.BOOK_DATA||[];render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'add_book_to_shelf',title:'加入书架',description:'将预设书库中的一本书加入个人书架，并同步更新当前页面。',inputSchema:{type:'object',properties:{bookId:{type:'string',description:'预设书籍 ID'}},required:['bookId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input.bookId!=='string'||!book(input.bookId))throw new Error('找不到这本书');if(!member(input.bookId))addBook(input.bookId);return {bookId:input.bookId,status:member(input.bookId)?.status||null}}})).catch(()=>{})}catch(e){}}

function applyCanvasScale(){document.documentElement.style.setProperty("--v5-scale",String(Math.min(1,window.innerWidth/1920)))}
applyCanvasScale();window.addEventListener("resize",applyCanvasScale);
